version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 3001:3001
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=BOOKS
      - MYSQL_USER=root_total
      - MYSQL_PASSWORD=password