version: "3.9"

networks:
  app_net:
    driver: bridge

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 3001:3001
    depends_on:
      - mysql
    networks:
      - app_net

  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=MANUAL
    hostname: mysql
    ports:
      - 3306:3306
    networks:
      - app_net
